house<-read.table("./household_power_consumption.txt",sep=";")
b<-filter(house,house$V1=="2/2/2007")
a<-filter(house,house$V1=="1/2/2007")
data<-rbind(a,b)
Datetime<-paste(data$V1,data$V2)
time<-as.POSIXlt(Datetime,format="%d/%m/%Y %H:%M:%S")
with(data,plot(time,data$V7,type="l",ylab="Energy sub metering",xlab=""))
with(data,lines(time,data$V8,col="red"))
with(data,lines(time,data$V9,col="blue"))
legend("topright",lty=c(1,1,1),col=c("black","red","blue"),legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"))
dev.copy(png,file="plot3.png")
dev.off()
