house<-read.table("./household_power_consumption.txt",sep=";")
b<-filter(house,house$V1=="2/2/2007")
a<-filter(house,house$V1=="1/2/2007")
data<-rbind(a,b)
Datetime<-paste(data$V1,data$V2)
time<-as.POSIXlt(Datetime,format="%d/%m/%Y %H:%M:%S")
par(mfrow=c(2,2),mar=c(4,4,1,1),oma=c(0,0,0,0))
plot(time,data$V3,type="l",ylab="Global Active Power (kilowatts)",xlab="")
plot(time,data$V5,type="l",ylab="Voltage",xlab="datetime")
with(data,plot(time,data$V7,type="l",ylab="Energy sub metering",xlab=""))
with(data,lines(time,data$V8,col="red"))
with(data,lines(time,data$V9,col="blue"))
legend("topright",lty=c(1,1,1),col=c("black","red","blue"),legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),cex=0.5)
plot(time,data$V4,type="l",ylab="Global reactive power",xlab="datetime")
dev.copy(png,file="plot4.png")
dev.off()
