house<-read.table("./household_power_consumption.txt",sep=";")
b<-filter(house,house$V1=="2/2/2007")
a<-filter(house,house$V1=="1/2/2007")
data<-rbind(a,b)
Datetime<-paste(data$V1,data$V2)
time<-as.POSIXlt(Datetime,format="%d/%m/%Y %H:%M:%S")
plot(time,data$V3,type="l",ylab="Global Active Power (kilowatts)",xlab="")
dev.copy(png,file="plot2.png")
dev.off()
